# see https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - errname
    - exhaustive
    - exportloopref
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - maintidx
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(kwo.dev/dayone2md)
  maintidx:
    # Show functions with maintainability index lower than N.
    # A high index indicates better maintainability (it's kind of the opposite of complexity).
    # Default: 20
    under: 30

