version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - gosec
    - govet
    - importas
    - ineffassign
    - maintidx
    - makezero
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    maintidx:
      under: 30
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kwo/dayone2md)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
