# documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/dayone2md
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tgz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

env_files:
  github_token: ./env

release:
  github:
    owner: kwo
    name: dayone2md

  mode: replace
