-- name: GetEntries :many
SELECT e.ZUUID, e.ZCREATIONDATE, e.ZMODIFIEDDATE, e.ZTIMEZONE, e.ZDURATION,
e.ZISPINNED, e.ZSTARRED, e.ZISALLDAY,
e.ZMARKDOWNTEXT, e.ZEDITINGTIME,
e.ZCREATIONDEVICE, e.ZCREATIONDEVICETYPE, e.ZCREATIONDEVICEMODEL, e.ZCREATIONOSNAME, e.ZCREATIONOSVERSION,
GROUP_CONCAT(t.ZNAME, ',') AS tags,
e.ZLOCATION, l.ZUSERLABEL, l.ZLATITUDE, l.ZLONGITUDE, l.ZALTITUDE, l.ZPLACENAME, l.ZLOCALITYNAME, l.ZADMINISTRATIVEAREA, l.ZCOUNTRY,
e.ZWEATHER, w.ZCONDITIONSDESCRIPTION, w.ZMOONPHASE, w.ZMOONPHASECODE, w.ZPRESSUREMB, w.ZRELATIVEHUMIDITY, w.ZSUNRISEDATE, w.ZSUNSETDATE, w.ZTEMPERATURECELSIUS, w.ZVISIBILITYKM, w.ZWEATHERCODE, w.ZWEATHERSERVICENAME, w.ZWINDBEARING, w.ZWINDSPEEDKPH
FROM ZENTRY e
JOIN ZJOURNAL j ON (e.ZJOURNAL = j.Z_PK)
LEFT JOIN Z_12TAGS et ON (et.Z_12ENTRIES = e.Z_PK)
LEFT JOIN ZTAG t ON (t.Z_PK = et.Z_54TAGS1)
LEFT JOIN ZLOCATION l ON (l.Z_PK = e.ZLOCATION)
LEFT JOIN ZWEATHER w ON (w.Z_PK = e.ZWEATHER)
WHERE j.ZNAME = ?
GROUP BY e.ZUUID;

-- name: GetPhotos :many
SELECT e.ZUUID, a.ZTYPE, a.ZFILENAME, a.ZIDENTIFIER, a.ZMD5
FROM ZATTACHMENT a
JOIN ZENTRY e ON (e.Z_PK = a.ZENTRY);
